### ISSUE TITLE
Amazon Firehose support

### ISSUE THREAD

**Issue by matt2000** [sharethrough/flume-kinesis#4]
Is it possible to use this Sink with Amazon's Kinesis Firehose Service? It seems Firehose streams are not  exactly the same as Kinesis Steams. When I set the Sink streamName to my Kinesis Stream, I get a failure in the Flume log like this:

com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream mystream_firehose under account 111111111111 not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 1234c78d-a998a-55c5-1234-123abc123456)

When I set the endpoint to http://kinesis.us-west-2.amazonaws.com, I get this Failure:

com.amazonaws.AmazonServiceException: null (Service: AmazonKinesis; Status Code: 400; Error Code: UnknownOperationException; Request ID:  1234c78d-a998a-55c5-1234-123abc123457)

**Comment by russellcardullo** [comment]
Unfortunately the API is slightly different between Kinesis Streams and Kinesis Firehose.  

A Kinesis Stream write would look like:
```
// com.amazonaws.services.kinesis.model.PutRecordRequest
PutRecordRequest putRecordRequest  = new PutRecordRequest();
putRecordRequest.setStreamName("DataStream");
```

whereas a Kinesis Firehose write would look like:
```
// com.amazonaws.services.kinesisfirehose.model.PutRecordRequest
PutRecordRequest putRecordRequest = new PutRecordRequest();
putRecordRequest.setDeliveryStreamName(deliveryStreamName);
```

I haven't looked too much into other API differences between writing to Kinesis Firehose vs Kinesis Streams but it might be possible to write to either based on some configuration value.  If you have an idea for a PR I'd be happy to take a look.  Otherwise I might look into this in the next week or so.

Maybe something in the configuration like this?
```
streamName = [stream | firehose] (default to stream)
```

**Comment by matt2000** [comment]
https://github.com/sharethrough/flume-kinesis/pull/5

**Comment by matt2000** [comment]
Thanks for accepting the PR!

**Comment by goldengate41** [comment]
I am facing the same error for Kinesis Firehose, please let me know if this is resolved.
